name: CI
on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    name: Build on Latest macOS
    runs-on: macOS-latest
    strategy:
      matrix:
        sap-version:
          - '1.0.0'
          - '1.0.1'
          - '1.0.2'
          - '1.0.3'
